FROM apache/airflow:2.8.1

USER root
# We need these for the postgres driver to compile/link correctly
RUN apt-get update && apt-get install -y openjdk-17-jdk libpq-dev gcc

USER airflow
# Install everything in one clean layer
RUN pip install --no-cache-dir \
    pyspark==3.5.1 \
    delta-spark==3.1.0 \
    apache-airflow-providers-postgres \
    apache-airflow-providers-apache-spark \
    psycopg2-binary \
    boto3